name: nadia-cox7a
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - numpy
  - scipy
  - dask
  - dask-labextension
  - dask-image
  - zarr  
  - numcodecs
  - imageio
  - ipywidgets
  - pandas
  - scikit-image
  - matplotlib
  - matplotlib-scalebar
  - seaborn
  - tqdm
  - statsmodels
  - scikit-learn
  - openpyxl
  - xlwt
